# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License.

param([object] $CurrentTestData, [object] $AllVmData)

function Install-HammerDB {
	Write-LogInfo "Install libmysqlclient-dev on client VM"
	$cmd = ". utils.sh && update_repos && install_package libmysqlclient-dev"
	Run-LinuxCmd -ip $serverPublicIP -port $serverSSHPort -username $username `
		-password $password -command $cmd -runAsSudo

	# Download and install HammerDB
	Run-LinuxCmd -ip $allVMData.PublicIP -port $allVMData.SSHPort -username $superuser `
		-password $password -command "wget -q ${HAMMERDB_URL}/${HAMMERDB_PACKAGE}" -ignoreLinuxExitCode | Out-Null
	if (-not $?) {
		Write-LogErr "Unable to download HammerDB, please check the download URL!"
		$currentTestResult.TestResult = Get-FinalResultHeader -resultarr "ABORTED"
		return $currentTestResult
	}

	Run-LinuxCmd -ip $allVMData.PublicIP -port $allVMData.SSHPort -username $superuser `
		-password $password -command "chmod 755 ./${HAMMERDB_PACKAGE} && ./${HAMMERDB_PACKAGE} --mode silent" `
		-ignoreLinuxExitCode | Out-Null
	if (-not $?) {
		Write-LogErr "Unable to install HammerDB!"
		$currentTestResult.TestResult = Get-FinalResultHeader -resultarr "FAILED"
		return $currentTestResult
	}
}

function Main {
	param ($TestParams, $AllVmData)

	# Create test result
	$resultArr = @()
	$currentTestResult = Create-TestResultObject

	try {
		$noClient = $true
		$noServer = $true
		foreach ($vmData in $allVMData) {
			if ($vmData.RoleName -imatch "client") {
				$clientVMData = $vmData
				$noClient = $false
			}
			elseif ($vmData.RoleName -imatch "server") {
				$noServer = $false
				$serverVMData = $vmData
			}
		}
		if ($noClient) {
			Throw "No master VM defined. Be sure that, Client VM role name matches with the pattern `"*master*`". Aborting Test."
		}
		if ($noServer) {
			Throw "No slave VM defined. Be sure that, Server machine role names matches with pattern `"*slave*`". Aborting Test."
		}

		Write-LogInfo "Client VM details :"
		Write-LogInfo "  RoleName : $($clientVMData.RoleName)"
		Write-LogInfo "  Public IP : $($clientVMData.PublicIP)"
		Write-LogInfo "  SSH Port : $($clientVMData.SSHPort)"
		Write-LogInfo "  Internal IP : $($clientVMData.InternalIP)"
		Write-LogInfo "Server VM details :"
		Write-LogInfo "  RoleName : $($serverVMData.RoleName)"
		Write-LogInfo "  Public IP : $($serverVMData.PublicIP)"
		Write-LogInfo "  SSH Port : $($serverVMData.SSHPort)"
		Write-LogInfo "  Internal IP : $($serverVMData.InternalIP)"

		# Checking automation compatibility
		if (! @("UBUNTU").contains($global:detectedDistro)) {
			Write-LogWarn "Unsupported distro in automation: ${global:detectedDistro}"
			return $global:ResultSkipped
		}

		# Enable passwordless authentication across all VMs
		Provision-VMsForLisa -allVMData $allVMData -installPackagesOnRoleNames "none"
		#endregion

		Write-LogInfo "Generating constants.sh..."
		$constantsFile = "$LogDir\constants.sh"
		Set-Content -Value "#Generated by Azure Automation." -Path $constantsFile
		Add-Content -Value "vms=$($serverVMData.RoleName),$($clientVMData.RoleName)" -Path $constantsFile
		Add-Content -Value "server=$($serverVMData.InternalIP)" -Path $constantsFile
		Add-Content -Value "client=$($clientVMData.InternalIP)" -Path $constantsFile

		foreach ($param in $currentTestData.TestParameters.param) {
			Add-Content -Value "$param" -Path $constantsFile
		}

		Write-LogInfo "constants.sh created successfully..."
		Write-LogInfo (Get-Content -Path $constantsFile)
		#endregion

		#region INSTALL CONFIGURE MySQL
		$install_configure_mysql = @"
cd /root/
./mysql_setup.sh > mysqlConsoleLogs.txt 2>&1
. utils.sh
collect_VM_properties
"@
		Set-Content "$LogDir\StartMySQLSetup.sh" $install_configure_mysql
		Copy-RemoteFiles -uploadTo $clientVMData.PublicIP -port $clientVMData.SSHPort `
			-files "$LogDir\StartMySQLSetup.sh" -username $superUser -password $password -upload

		Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort `
			-username $superUser -password $password -command "chmod +x *.sh" | Out-Null
		$testJob = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort `
			-username $superUser -password $password -command "./StartMySQLSetup.sh" -RunInBackground
		#endregion

		#region MONITOR INSTALL CONFIGURE MySQL server
		while ((Get-Job -Id $testJob).State -eq "Running") {
			$currentStatus = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort `
				-username $superUser -password $password -command "tail -2 mysqlConsoleLogs.txt | head -1"
			Write-LogInfo "Current Test Status : $currentStatus"
			Wait-Time -seconds 30
		}
		$mysqlStatus = Run-LinuxCmd -ip $clientVMData.PublicIP -port $clientVMData.SSHPort `
			-username $superUser -password $password -command "cat /root/state.txt"
		$testResult = Get-TestStatus $mysqlStatus

		Copy-RemoteFiles -downloadFrom $clientVMData.PublicIP -port $clientVMData.SSHPort `
			-username $superUser -password $password -download -downloadTo $LogDir -files "*.txt, *.log"
	} catch {
		$ErrorMessage =  $_.Exception.Message
		$ErrorLine = $_.InvocationInfo.ScriptLineNumber
		Write-LogErr "EXCEPTION : $ErrorMessage at line: $ErrorLine"
		$testResult = "FAIL"
	} finally {
		if (!$testResult) {
			$testResult = "Aborted"
		}
		$resultArr += $testResult
	}
	$currentTestResult.TestResult = Get-FinalResultHeader -resultarr $resultArr
	return $currentTestResult
}

Main -TestParams (ConvertFrom-StringData $TestParams.Replace(";","`n")) -AllVmData $AllVmData